/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conexaoBanco;

import java.sql.Connection;
import javax.swing.SwingUtilities;

public class App {

	public static void main(String[] args) {
		// Cria e exibe a interface gráfica na EDT
		SwingUtilities.invokeLater(() -> {
			Main main = new Main(); // Passa a conexão para o construtor
			main.setVisible(true);
		});
	}
}
