/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BCrypt;

import BCrypt.model.Database;
import BCrypt.model.User;
import BCrypt.model.UserDAO;

public class App {
	public static void main(String[] args) {
		UserDAO userDAO =  new UserDAO();
		
		
		//userDAO.insertUser(user);
		//userDAO.deleteUser(user);
	}
}
