/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.biblioMVC.view;

import com.example.biblioMVC.controller.LivroController;
import com.example.biblioMVC.model.Livro;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emanu
 */
public class Frmlivro extends javax.swing.JFrame {

	/**
	 * Creates new form Frmlivro
	 */
	private final LivroController livroController;
	private String tituloSelecionado;
	private String autorSelecionado;
	private int anoSelecionado;

	public Frmlivro() {
		initComponents();
		livroController = new LivroController();
		attTableLivros();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCadastroLivro = new javax.swing.JPanel();
        inputTitulo = new javax.swing.JTextField();
        tituloLbl = new javax.swing.JLabel();
        autorLbl = new javax.swing.JLabel();
        inputAutor = new javax.swing.JTextField();
        anoLbl = new javax.swing.JLabel();
        inputAno = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        PanelAtualizarLivro = new javax.swing.JPanel();
        inputTituloAtt = new javax.swing.JTextField();
        tituloLbl3 = new javax.swing.JLabel();
        autorLbl3 = new javax.swing.JLabel();
        inputAutorAtt = new javax.swing.JTextField();
        anoLbl2 = new javax.swing.JLabel();
        inputAnoAtt = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        PanelDeletarLivro = new javax.swing.JPanel();
        tituloLbl1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        btnRemover = new javax.swing.JButton();
        PanelTableLivros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BiblioMVC");
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(PanelTableLivros.getBackground());
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        PanelCadastroLivro.setBackground(new java.awt.Color(51, 51, 51));
        PanelCadastroLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        inputTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTituloActionPerformed(evt);
            }
        });

        tituloLbl.setForeground(new java.awt.Color(255, 255, 255));
        tituloLbl.setText("Titulo:");

        autorLbl.setForeground(new java.awt.Color(255, 255, 255));
        autorLbl.setText("Autor:");

        inputAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAutorActionPerformed(evt);
            }
        });

        anoLbl.setForeground(new java.awt.Color(255, 255, 255));
        anoLbl.setText("Ano:");

        btnAdicionar.setBackground(new java.awt.Color(102, 102, 102));
        btnAdicionar.setForeground(new java.awt.Color(0, 204, 102));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseExited(evt);
            }
        });
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastroLivroLayout = new javax.swing.GroupLayout(PanelCadastroLivro);
        PanelCadastroLivro.setLayout(PanelCadastroLivroLayout);
        PanelCadastroLivroLayout.setHorizontalGroup(
            PanelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAutor)
                    .addComponent(inputTitulo)
                    .addComponent(anoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAno)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCadastroLivroLayout.setVerticalGroup(
            PanelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(autorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Adicionar", PanelCadastroLivro);

        PanelAtualizarLivro.setBackground(new java.awt.Color(51, 51, 51));
        PanelAtualizarLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atualizar Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        inputTituloAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTituloAttActionPerformed(evt);
            }
        });

        tituloLbl3.setForeground(new java.awt.Color(255, 255, 255));
        tituloLbl3.setText("Titulo:");

        autorLbl3.setForeground(new java.awt.Color(255, 255, 255));
        autorLbl3.setText("Autor:");

        inputAutorAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAutorAttActionPerformed(evt);
            }
        });

        anoLbl2.setForeground(new java.awt.Color(255, 255, 255));
        anoLbl2.setText("Ano:");

        btnAtualizar.setBackground(new java.awt.Color(102, 102, 102));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 0));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorder(null);
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.setDefaultCapable(false);
        btnAtualizar.setDoubleBuffered(true);
        btnAtualizar.setFocusPainted(false);
        btnAtualizar.setContentAreaFilled(true);
        btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseExited(evt);
            }
        });
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAtualizarLivroLayout = new javax.swing.GroupLayout(PanelAtualizarLivro);
        PanelAtualizarLivro.setLayout(PanelAtualizarLivroLayout);
        PanelAtualizarLivroLayout.setHorizontalGroup(
            PanelAtualizarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtualizarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAtualizarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autorLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAutorAtt)
                    .addComponent(inputTituloAtt)
                    .addComponent(anoLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAnoAtt)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAtualizarLivroLayout.setVerticalGroup(
            PanelAtualizarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtualizarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTituloAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(autorLbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAutorAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anoLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAnoAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Atualizar", PanelAtualizarLivro);

        PanelDeletarLivro.setBackground(new java.awt.Color(51, 51, 51));
        PanelDeletarLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exclusão de Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tituloLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tituloLbl1.setForeground(new java.awt.Color(255, 255, 255));
        tituloLbl1.setText("Como Funciona ?");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 102, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Para  deletar algum livro, apenas selecione qual deseja, e aperte a tecla \"Delete\". Caso não funcione, use o botão abaixo.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jTextArea1.setRequestFocusEnabled(false);

        btnRemover.setBackground(new java.awt.Color(102, 102, 102));
        btnRemover.setForeground(new java.awt.Color(255, 0, 0));
        btnRemover.setText("Remover");
        btnRemover.setBorderPainted(false);
        btnRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoverMouseExited(evt);
            }
        });
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDeletarLivroLayout = new javax.swing.GroupLayout(PanelDeletarLivro);
        PanelDeletarLivro.setLayout(PanelDeletarLivroLayout);
        PanelDeletarLivroLayout.setHorizontalGroup(
            PanelDeletarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeletarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDeletarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDeletarLivroLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelDeletarLivroLayout.setVerticalGroup(
            PanelDeletarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeletarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Excluir", PanelDeletarLivro);

        PanelTableLivros.setBackground(new java.awt.Color(51, 51, 51));
        PanelTableLivros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBackground(PanelTableLivros.getBackground());
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Livros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tableLivros.setAutoCreateRowSorter(true);
        tableLivros.setBackground(new java.awt.Color(255, 255, 255));
        tableLivros.setForeground(new java.awt.Color(0, 0, 0));
        tableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Autor", "Ano de Lançamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLivros.setFocusable(false);
        tableLivros.setGridColor(new java.awt.Color(102, 102, 102));
        tableLivros.setShowGrid(false);
        tableLivros.setShowHorizontalLines(true);
        tableLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLivrosMouseClicked(evt);
            }
        });
        tableLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableLivrosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableLivros);
        //tableLivros.getTableHeader().setVisible(false);

        javax.swing.GroupLayout PanelTableLivrosLayout = new javax.swing.GroupLayout(PanelTableLivros);
        PanelTableLivros.setLayout(PanelTableLivrosLayout);
        PanelTableLivrosLayout.setHorizontalGroup(
            PanelTableLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(PanelTableLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTableLivrosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PanelTableLivrosLayout.setVerticalGroup(
            PanelTableLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PanelTableLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTableLivrosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelTableLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelTableLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTituloActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputTituloActionPerformed

    private void inputAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAutorActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputAutorActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
		// TODO add your handling code here:
		String titulo = inputTitulo.getText();
		String autor = inputAutor.getText();
		String ano = inputAno.getText();

		if (titulo.isEmpty() && autor.isEmpty() && ano.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Aviso: Alguns dos campos está em branco!\nPreencha todos os campos!", "Cuidado!", JOptionPane.WARNING_MESSAGE);
		} else {
			String success = livroController.adicionarLivro(titulo, autor, ano);

			JOptionPane.showMessageDialog(null, "Sucesso: " + success, "Success", JOptionPane.INFORMATION_MESSAGE);
			attTableLivros();

			inputTitulo.setText("");
			inputAutor.setText("");
			inputAno.setText("");

			//JOptionPane.showMessageDialog(null, "Ops!... Algo deu errado. \n" + success, "Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseEntered
		// TODO add your handling code here:
		btnAdicionar.setBackground(new java.awt.Color(0,204,102));
		btnAdicionar.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_btnAdicionarMouseEntered

    private void inputTituloAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTituloAttActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputTituloAttActionPerformed

    private void inputAutorAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAutorAttActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputAutorAttActionPerformed

    private void btnAtualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseEntered
		// TODO add your handling code here:
		btnAtualizar.setBackground(new java.awt.Color(255, 255, 0));
		btnAtualizar.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_btnAtualizarMouseEntered

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
		// TODO add your handling code here:
		String newTitle = inputTituloAtt.getText();
		String newAutor = inputAutorAtt.getText();
		String newAno = inputAnoAtt.getText();

		if (newTitle.isEmpty() && newAutor.isEmpty() && newAno.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Aviso: Alguns dos campos está em branco!\nPreencha todos os campos!", "Cuidado!", JOptionPane.WARNING_MESSAGE);
		} else {
			String success = livroController.atualizarLivro(tituloSelecionado, autorSelecionado, newTitle, newAutor, newAno);

			JOptionPane.showMessageDialog(null, success, "Success", JOptionPane.INFORMATION_MESSAGE);
			attTableLivros();

			//JOptionPane.showMessageDialog(null, "Ops!... Algo deu errado. \n" + success, "Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tableLivrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableLivrosKeyPressed
		// TODO add your handling code here:
		if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
			//Pegar a linha selecionada
			int selectedRow = tableLivros.getSelectedRow();
			
			System.out.println(""+selectedRow);
			
			if (selectedRow != -1) {
				String tituloLivro = (String) tableLivros.getValueAt(selectedRow, 0); //Pego o valor da celula que corresponde a linha tal x coluna tal
				String autorLivro = (String) tableLivros.getValueAt(selectedRow, 1);

				/*
				System.out.println(tituloLivro);
				System.out.println(autorLivro);
				 */
				String success = livroController.removerLivro(tituloLivro, autorLivro);

				JOptionPane.showMessageDialog(null, success, "Informando", JOptionPane.INFORMATION_MESSAGE);
				attTableLivros();
			}
		}
    }//GEN-LAST:event_tableLivrosKeyPressed

    private void tableLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLivrosMouseClicked
		// TODO add your handling code here:
		int linhaSelecionada = tableLivros.getSelectedRow();

		if (linhaSelecionada != -1) {
			tituloSelecionado = (String) tableLivros.getValueAt(linhaSelecionada, 0);
			autorSelecionado = (String) tableLivros.getValueAt(linhaSelecionada, 1);
			anoSelecionado = (int) tableLivros.getValueAt(linhaSelecionada, 2);

			inputTituloAtt.setText(tituloSelecionado);
			inputAutorAtt.setText(autorSelecionado);
			inputAnoAtt.setText("" + anoSelecionado);
		}
    }//GEN-LAST:event_tableLivrosMouseClicked

    private void btnAtualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseExited
        // TODO add your handling code here:
		btnAtualizar.setBackground(new java.awt.Color(102,102,102));
		btnAtualizar.setForeground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_btnAtualizarMouseExited

    private void btnAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseExited
        // TODO add your handling code here:
		btnAdicionar.setForeground(new java.awt.Color(0,204,102));
		btnAdicionar.setBackground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_btnAdicionarMouseExited

    private void btnRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverMouseEntered

    private void btnRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverMouseExited

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
		int selectedRow = tableLivros.getSelectedRow();
			
			System.out.println(""+selectedRow);
			
			if (selectedRow != -1) {
				String tituloLivro = (String) tableLivros.getValueAt(selectedRow, 0); //Pego o valor da celula que corresponde a linha tal x coluna tal
				String autorLivro = (String) tableLivros.getValueAt(selectedRow, 1);

				/*
				System.out.println(tituloLivro);
				System.out.println(autorLivro);
				 */
				String success = livroController.removerLivro(tituloLivro, autorLivro);

				JOptionPane.showMessageDialog(null, success, "Informando", JOptionPane.INFORMATION_MESSAGE);
				attTableLivros();
			}
		
    }//GEN-LAST:event_btnRemoverActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frmlivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frmlivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frmlivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frmlivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frmlivro().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAtualizarLivro;
    private javax.swing.JPanel PanelCadastroLivro;
    private javax.swing.JPanel PanelDeletarLivro;
    private javax.swing.JPanel PanelTableLivros;
    private javax.swing.JLabel anoLbl;
    private javax.swing.JLabel anoLbl2;
    private javax.swing.JLabel autorLbl;
    private javax.swing.JLabel autorLbl3;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTextField inputAno;
    private javax.swing.JTextField inputAnoAtt;
    private javax.swing.JTextField inputAutor;
    private javax.swing.JTextField inputAutorAtt;
    private javax.swing.JTextField inputTitulo;
    private javax.swing.JTextField inputTituloAtt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tableLivros;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JLabel tituloLbl1;
    private javax.swing.JLabel tituloLbl3;
    // End of variables declaration//GEN-END:variables

	public void attTableLivros() {
		// Recupera os dados dos usuários do banco de dados
		ArrayList<Livro> listaLivros = livroController.listarLivros();

		// Obtém o modelo da tabela
		DefaultTableModel model = (DefaultTableModel) tableLivros.getModel();

		// Limpa a tabela
		model.setRowCount(0);

		// Adiciona os novos dados à tabela
		for (Livro livro : listaLivros) {
			// Cria um array de objetos com os dados do usuário
			Object[] rowData = {livro.getTitulo(), livro.getAutor(), livro.getAnoPublicacao()};
			// Adiciona a linha ao modelo da tabela
			model.addRow(rowData);
		}
	}

	private Color Color(int i, int i0, int i1) {
		throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
	}
}
