/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.biblioMVC.view;

import com.example.biblioMVC.controller.LivroController;
import com.example.biblioMVC.model.Livro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emanu
 */
public class Frmlivro extends javax.swing.JFrame {

	/**
	 * Creates new form Frmlivro
	 */
	private final LivroController livroController;

	public Frmlivro() {
		initComponents();
		livroController = new LivroController();
		attTableLivros();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCadastroLivro = new javax.swing.JPanel();
        inputTitulo = new javax.swing.JTextField();
        tituloLbl = new javax.swing.JLabel();
        autorLbl = new javax.swing.JLabel();
        inputAutor = new javax.swing.JTextField();
        anoLbl = new javax.swing.JLabel();
        inputAno = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        PanelDeletarLivro = new javax.swing.JPanel();
        inputTituloDel = new javax.swing.JTextField();
        tituloLbl1 = new javax.swing.JLabel();
        autorLbl1 = new javax.swing.JLabel();
        inputAutorDel = new javax.swing.JTextField();
        btnDeletar = new javax.swing.JButton();
        PanelAtualizarLivro = new javax.swing.JPanel();
        inputTitulo2 = new javax.swing.JTextField();
        tituloLbl3 = new javax.swing.JLabel();
        autorLbl3 = new javax.swing.JLabel();
        inputAutor2 = new javax.swing.JTextField();
        anoLbl2 = new javax.swing.JLabel();
        inputAno2 = new javax.swing.JTextField();
        btnAdicionar2 = new javax.swing.JButton();
        PanelTableLivros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BiblioMVC");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PanelCadastroLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 14))); // NOI18N

        inputTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTituloActionPerformed(evt);
            }
        });

        tituloLbl.setText("Titulo:");

        autorLbl.setText("Autor:");

        inputAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAutorActionPerformed(evt);
            }
        });

        anoLbl.setText("Ano:");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseEntered(evt);
            }
        });
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastroLivroLayout = new javax.swing.GroupLayout(PanelCadastroLivro);
        PanelCadastroLivro.setLayout(PanelCadastroLivroLayout);
        PanelCadastroLivroLayout.setHorizontalGroup(
            PanelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAutor)
                    .addComponent(inputTitulo)
                    .addComponent(anoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAno)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCadastroLivroLayout.setVerticalGroup(
            PanelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(autorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Adicionar", PanelCadastroLivro);

        PanelDeletarLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exclusão de Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 14))); // NOI18N

        inputTituloDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTituloDelActionPerformed(evt);
            }
        });

        tituloLbl1.setText("Titulo:");

        autorLbl1.setText("Autor:");

        inputAutorDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAutorDelActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeletarMouseEntered(evt);
            }
        });
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDeletarLivroLayout = new javax.swing.GroupLayout(PanelDeletarLivro);
        PanelDeletarLivro.setLayout(PanelDeletarLivroLayout);
        PanelDeletarLivroLayout.setHorizontalGroup(
            PanelDeletarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeletarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDeletarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autorLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAutorDel)
                    .addComponent(inputTituloDel)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDeletarLivroLayout.setVerticalGroup(
            PanelDeletarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeletarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTituloDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(autorLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAutorDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnDeletar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Excluir", PanelDeletarLivro);

        PanelAtualizarLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 14))); // NOI18N

        inputTitulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTitulo2ActionPerformed(evt);
            }
        });

        tituloLbl3.setText("Titulo:");

        autorLbl3.setText("Autor:");

        inputAutor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAutor2ActionPerformed(evt);
            }
        });

        anoLbl2.setText("Ano:");

        btnAdicionar2.setText("Adicionar");
        btnAdicionar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionar2MouseEntered(evt);
            }
        });
        btnAdicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAtualizarLivroLayout = new javax.swing.GroupLayout(PanelAtualizarLivro);
        PanelAtualizarLivro.setLayout(PanelAtualizarLivroLayout);
        PanelAtualizarLivroLayout.setHorizontalGroup(
            PanelAtualizarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtualizarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAtualizarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autorLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAutor2)
                    .addComponent(inputTitulo2)
                    .addComponent(anoLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAno2)
                    .addComponent(btnAdicionar2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAtualizarLivroLayout.setVerticalGroup(
            PanelAtualizarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtualizarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(autorLbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anoLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnAdicionar2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Atualizar", PanelAtualizarLivro);

        PanelTableLivros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Livros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 3, 18))); // NOI18N

        tableLivros.setAutoCreateRowSorter(true);
        tableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Autor", "Ano de Lançamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLivros.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tableLivros);
        //tableLivros.getTableHeader().setVisible(false);

        javax.swing.GroupLayout PanelTableLivrosLayout = new javax.swing.GroupLayout(PanelTableLivros);
        PanelTableLivros.setLayout(PanelTableLivrosLayout);
        PanelTableLivrosLayout.setHorizontalGroup(
            PanelTableLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
            .addGroup(PanelTableLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTableLivrosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PanelTableLivrosLayout.setVerticalGroup(
            PanelTableLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PanelTableLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTableLivrosLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelTableLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelTableLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTituloActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputTituloActionPerformed

    private void inputAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAutorActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputAutorActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
		// TODO add your handling code here:
		String titulo = inputTitulo.getText();
		String autor = inputAutor.getText();
		String ano = inputAno.getText();
		
		if(titulo.isEmpty() && autor.isEmpty() && ano.isEmpty()){
			JOptionPane.showMessageDialog(null, "Aviso: Alguns dos campos está em branco!\nPreencha todos os campos!", "Cuidado!", JOptionPane.WARNING_MESSAGE);
		} else {
			String success = livroController.adicionarLivro(titulo, autor, ano);
			
			
			JOptionPane.showMessageDialog(null, "Sucesso: " + success, "Success", JOptionPane.INFORMATION_MESSAGE);
			attTableLivros();
			
			//JOptionPane.showMessageDialog(null, "Ops!... Algo deu errado. \n" + success, "Error", JOptionPane.ERROR_MESSAGE);
			
		}
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseEntered
		// TODO add your handling code here:

    }//GEN-LAST:event_btnAdicionarMouseEntered

    private void inputTituloDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTituloDelActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputTituloDelActionPerformed

    private void inputAutorDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAutorDelActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputAutorDelActionPerformed

    private void btnDeletarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarMouseEntered
		// TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarMouseEntered

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void inputTitulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTitulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTitulo2ActionPerformed

    private void inputAutor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAutor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAutor2ActionPerformed

    private void btnAdicionar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionar2MouseEntered

    private void btnAdicionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionar2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frmlivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frmlivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frmlivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frmlivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frmlivro().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAtualizarLivro;
    private javax.swing.JPanel PanelCadastroLivro;
    private javax.swing.JPanel PanelDeletarLivro;
    private javax.swing.JPanel PanelTableLivros;
    private javax.swing.JLabel anoLbl;
    private javax.swing.JLabel anoLbl2;
    private javax.swing.JLabel autorLbl;
    private javax.swing.JLabel autorLbl1;
    private javax.swing.JLabel autorLbl3;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAdicionar2;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JTextField inputAno;
    private javax.swing.JTextField inputAno2;
    private javax.swing.JTextField inputAutor;
    private javax.swing.JTextField inputAutor2;
    private javax.swing.JTextField inputAutorDel;
    private javax.swing.JTextField inputTitulo;
    private javax.swing.JTextField inputTitulo2;
    private javax.swing.JTextField inputTituloDel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableLivros;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JLabel tituloLbl1;
    private javax.swing.JLabel tituloLbl3;
    // End of variables declaration//GEN-END:variables

	public void attTableLivros() {
		// Recupera os dados dos usuários do banco de dados
		ArrayList<Livro> listaLivros = livroController.listarLivros();

		// Obtém o modelo da tabela
		DefaultTableModel model = (DefaultTableModel) tableLivros.getModel();

		// Limpa a tabela
		model.setRowCount(0);

		// Adiciona os novos dados à tabela
		for (Livro livro : listaLivros) {
			// Cria um array de objetos com os dados do usuário
			Object[] rowData = {livro.getTitulo(), livro.getAutor(), livro.getAnoPublicacao()};
			// Adiciona a linha ao modelo da tabela
			model.addRow(rowData);
		}
	}
}
