/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoLogin;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author NATANGABRIELWILDNERD
 */
public class System extends javax.swing.JFrame {

	private final Connection conexao;

	/**
	 * Creates new form System
	 */
	
	
	
	public System() {
		this.conexao = ConexaoSQLite.conectar();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        emailLogin = new javax.swing.JLabel();
        senhaLogin = new javax.swing.JLabel();
        inputEmailLogin = new javax.swing.JTextField();
        inputSenhaLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        PanelRegistro = new javax.swing.JPanel();
        registro = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        inputEmailRegistro = new javax.swing.JTextField();
        inputSenhaRegistro = new javax.swing.JPasswordField();
        btnRegistrar1 = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();
        inputSenhaRegistroConfirmar = new javax.swing.JPasswordField();
        confirmarSenha = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        inputNomeRegistro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        login.setFont(new java.awt.Font("Jersey 10", 0, 48)); // NOI18N
        login.setText("LOGIN");

        emailLogin.setFont(new java.awt.Font("Jersey 10", 0, 18)); // NOI18N
        emailLogin.setText("Email");

        senhaLogin.setFont(new java.awt.Font("Jersey 10", 0, 18)); // NOI18N
        senhaLogin.setText("Senha");

        inputEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailLoginActionPerformed(evt);
            }
        });

        btnLogin.setText("LOGAR");

        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhaLogin)
                            .addComponent(emailLogin)
                            .addComponent(inputEmailLogin)
                            .addComponent(inputSenhaLogin)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(login)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(senhaLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(PanelLogin, "PanelLogin");

        registro.setFont(new java.awt.Font("Jersey 10", 0, 48)); // NOI18N
        registro.setText("REGISTRO");

        email.setFont(new java.awt.Font("Jersey 10", 0, 18)); // NOI18N
        email.setText("Email");

        senha.setFont(new java.awt.Font("Jersey 10", 0, 18)); // NOI18N
        senha.setText("Senha");

        inputEmailRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailRegistroActionPerformed(evt);
            }
        });

        btnRegistrar1.setText("REGISTRAR");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });

        btnLogin1.setText("Logar");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        confirmarSenha.setFont(new java.awt.Font("Jersey 10", 0, 18)); // NOI18N
        confirmarSenha.setText("Confirme sua senha");

        nome.setFont(new java.awt.Font("Jersey 10", 0, 18)); // NOI18N
        nome.setText("Nome");

        inputNomeRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senha)
                            .addComponent(email)
                            .addComponent(inputEmailRegistro)
                            .addComponent(inputSenhaRegistro)
                            .addComponent(btnRegistrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(inputSenhaRegistroConfirmar)
                            .addComponent(confirmarSenha)
                            .addComponent(nome)
                            .addComponent(inputNomeRegistro)))
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(registro)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmailRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNomeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSenhaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(confirmarSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSenhaRegistroConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar1)
                .addGap(18, 18, 18)
                .addComponent(btnLogin1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelRegistro, "PanelRegistro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void inputEmailRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailRegistroActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void inputNomeRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeRegistroActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        // TODO add your handling code here:
		String nome = inputNomeRegistro.getText();
		String email = inputEmailRegistro.getText();
		String senha = inputSenhaRegistro.getText();
		
		if(senha.equals(inputSenhaRegistroConfirmar)){
			
		} else {
			JOptionPane.showMessageDialog(null, "Erro: Senhas não coincidem !", "Erro", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new System().setVisible(true);
				
			}
		});
	}
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JLabel confirmarSenha;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailLogin;
    private javax.swing.JTextField inputEmailLogin;
    private javax.swing.JTextField inputEmailRegistro;
    private javax.swing.JTextField inputNomeRegistro;
    private javax.swing.JPasswordField inputSenhaLogin;
    private javax.swing.JPasswordField inputSenhaRegistro;
    private javax.swing.JPasswordField inputSenhaRegistroConfirmar;
    private javax.swing.JLabel login;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel registro;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel senhaLogin;
    // End of variables declaration//GEN-END:variables

}
