/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClonePokemon;

import java.util.Scanner;

public class App {

	// Método para perguntar o nome do jogador, vai ser chamado como primeiro!
	public String askPlayerName(Scanner sc) {
		System.out.print("????? \nOla treinador! Qual seu nome? \n> ");
		String name = sc.nextLine();
		return name;
	}

	public void batalhar(Pokemon meuPokemon, Pokemon oponentePokemon, Scanner sc, Dados dados) {

		boolean emBatalha = true;

		while (meuPokemon.estaVivo() && oponentePokemon.estaVivo() && emBatalha) {
			// Exibe os status
			System.out.println("==============================================");
			System.out.println("|                              STATUS DE BATALHA                         |");
			System.out.println("|=============================================|");
			System.out.println("| Jogador: " + meuPokemon.getName() + " | Hp: " + meuPokemon.getHp());
			System.out.println("| Inimigo: " + oponentePokemon.getName() + " | Hp: " + oponentePokemon.getHp());
			System.out.println("|=============================================|");
			System.out.println("| 1. Atacar                                                                           |");
			System.out.println("| 3. Fugir                                                                       |");
			System.out.println("|=============================================|");
			System.out.print("> ");
			int escolha1 = sc.nextInt();

			sc.nextLine();

			boolean souMaisRapido = meuPokemon.getSpeed() > oponentePokemon.getSpeed();

			switch (escolha1) {
				case 1:
					if (souMaisRapido) {
						meuPokemon.atacar(oponentePokemon);
						oponentePokemon.atacar2(meuPokemon);

						System.out.print("\n> Voce atacou primeiro! Aperte ENTER para continuar");
						sc.nextLine();
					} else {
						oponentePokemon.atacar2(meuPokemon);
						meuPokemon.atacar(oponentePokemon);

						System.out.print("\n> O seu oponente atacou primeiro! Aperte ENTER para continuar");
						sc.nextLine();
					}
					
					if(!meuPokemon.estaVivo()){
						System.out.print("Voce morreu! Aperte ENTER para continuar!");
						sc.nextLine();
					} else if(!oponentePokemon.estaVivo()){
						System.out.print("Voce venceu! Aperte ENTER para continuar! Seu HP é:" + meuPokemon.getHp());
						sc.nextLine();
					}
					break;

				case 3:
					dados.rolarDados();

					if (meuPokemon.fugir(oponentePokemon, dados.somaResultDados())) {
						System.out.print("\n> Voce conseguiu escapar! Aperte ENTER para continuar");
						sc.nextLine();
						emBatalha = false;
					} else {
						System.out.print("\n> Voce nao conseguiu escapar! Aperte ENTER para continuar");
						sc.nextLine();
					}
					break;

				default:
					System.out.print("Escolha Invadia! Aperte ENTER para voltar ao menu. ");
					sc.nextLine();
					break;
			}
		}
	}

	public static void main(String[] args) {
		App app = new App();
		
		
		try {
			Scanner sc = new Scanner(System.in);
			Dados dados = new Dados();
			ProfessorOak  professorOak = new ProfessorOak();
			Pokemon pikachu0 = new Pikachu();
			
			
			
			Treinador player = new Treinador(app.askPlayerName(sc));
			Screen.clear();
			
			professorOak.introduction(player, sc, dados);
			
			app.batalhar(player.time.get(0), pikachu0, sc, dados);
			
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}
}
