/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClonePokemon;

import java.util.Scanner;

public class App {
	
	public static String localDoJogo;
	
	// Método para perguntar o nome do jogador, vai ser chamado como primeiro!
	public String askPlayerName(Scanner sc) {
		System.out.print("????? \nOla treinador! Qual seu nome? \n> ");
		String name = sc.nextLine();
		return name;
	}
	
	//Método de batalha;
	public void batalhar(Pokemon meuPokemon, Pokemon oponentePokemon, Scanner sc, Dados dados) {

		boolean emBatalha = true;

		while (meuPokemon.estaVivo() && oponentePokemon.estaVivo() && emBatalha) {
			Screen.clearSimple();
			
			// Exibe os status
			System.out.println("\n==============================================");
			System.out.println("|                              BATALHA		                            |");
			System.out.println("|=============================================|");
			System.out.println("| Jogador: " + meuPokemon.getName() + " | Hp: " + meuPokemon.getHp());
			System.out.println("| Inimigo: " + oponentePokemon.getName() + " | Hp: " + oponentePokemon.getHp());
			System.out.println("|=============================================|");
			System.out.println("| 1. Atacar                                                                           |");
			System.out.println("| 3. Fugir                                                                             |");
			System.out.println("|=============================================|");
			System.out.print("> ");
			int escolha1 = sc.nextInt();

			sc.nextLine();

			boolean souMaisRapido = meuPokemon.getSpeed() > oponentePokemon.getSpeed();

			switch (escolha1) {
				case 1:
					//Checar quem ataca primeiro;
					if (souMaisRapido) {
						meuPokemon.atacar(oponentePokemon);
						oponentePokemon.atacar2(meuPokemon);

						System.out.print("\n> Voce atacou primeiro! Aperte ENTER para continuar");
						sc.nextLine();
					} else {
						oponentePokemon.atacar2(meuPokemon);
						meuPokemon.atacar(oponentePokemon);

						System.out.print("\n> O seu oponente atacou primeiro! Aperte ENTER para continuar");
						sc.nextLine();
					}
					
					//Checar se morreu;
					if(!meuPokemon.estaVivo()){
						System.out.print("Voce morreu! Aperte ENTER para continuar!");
						sc.nextLine();
					} else if(!oponentePokemon.estaVivo()){
						System.out.print("Voce venceu! Aperte ENTER para continuar! Seu HP é:" + meuPokemon.getHp());
						sc.nextLine();

					}
					break;

				case 3:
					dados.rolarDados();
					
					//Se o resultado dos dados for maior que a velocidade do inimigo, eu consigo;
					if (meuPokemon.fugir(oponentePokemon, dados.somaResultDados())) {
						System.out.print("\n> Voce conseguiu escapar! Aperte ENTER para continuar");
						sc.nextLine();
						emBatalha = false;
					} else {
						System.out.print("\n> Voce nao conseguiu escapar! Aperte ENTER para continuar");
						sc.nextLine();
					}
					break;

				default:
					System.out.print("Escolha Invadia! Aperte ENTER para voltar ao menu. ");
					sc.nextLine();
					break;
			}
		}
	}

	public static void main(String[] args) {
		App app = new App();
		Dados dados = new Dados();
		ProfessorOak  professorOak = new ProfessorOak();
		Rota1 rota1 = new Rota1();
		ViridianCity viridianCity = new ViridianCity();
		Rota2 rota2 = new Rota2(dados);
		
		
		try {
			Scanner sc = new Scanner(System.in);
			Treinador player = new Treinador(app.askPlayerName(sc));
			
			professorOak.introduction(player, sc, dados);
			rota1.init(app, player, sc, dados);
			
			while(player.time.get(0).estaVivo()) {
				if(App.localDoJogo.equals("Viridian")){
					viridianCity.init(sc, player);
				} else if(App.localDoJogo.equals("Rota 2")) {
					rota2.init2(sc, dados, app, player);
				}
			}
			
			System.out.println("Fim de Jogo!");
			
			

		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}
}
