/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClonePokemon;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author gabri
 */
public class TelaBatalha extends javax.swing.JFrame {

	/**
	 * Creates new form TelaBatalha
	 */
	public TelaBatalha() {
		initComponents();
	}
	
	public TelaBatalha(Treinador player, Pokemon oponente) {
		this.player = player;
		this.pokemonOponente = oponente;
		
		initComponents();	
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BtnFugir = new javax.swing.JButton();
        BtnAtacar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        LblNomeMyPokemon = new javax.swing.JLabel();
        LblHpMyPokemon = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LblNomeOponPokemon = new javax.swing.JLabel();
        LblHpOponPokemon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StatusBattleTxtArea = new javax.swing.JTextArea();
        LblPokemonOponente = new javax.swing.JLabel();
        LblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(560, 450));
        setPreferredSize(new java.awt.Dimension(560, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);

        BtnFugir.setBackground(new java.awt.Color(153, 255, 51));
        BtnFugir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BtnFugir.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        BtnFugir.setText("Fugir");
        BtnFugir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnAtacar.setBackground(new java.awt.Color(255, 84, 114));
        BtnAtacar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BtnAtacar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAtacar.setText("Atacar");
        BtnAtacar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtacarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnFugir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFugir)
                    .addComponent(BtnAtacar))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(325, 341, 207, 59);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblNomeMyPokemon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblNomeMyPokemon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblNomeMyPokemon.setText(player.time.get(0).getName());

        LblHpMyPokemon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LblHpMyPokemon.setText(String.valueOf(player.time.get(0).getHp()));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblHpMyPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNomeMyPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblNomeMyPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblHpMyPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(320, 210, 200, 70);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblNomeOponPokemon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblNomeOponPokemon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblNomeOponPokemon.setText(pokemonOponente.getName());

        LblHpOponPokemon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LblHpOponPokemon.setText(String.valueOf(pokemonOponente.getHp()));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNomeOponPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblHpOponPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblNomeOponPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblHpOponPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(12, 13, 190, 71);

        StatusBattleTxtArea.setEditable(false);
        StatusBattleTxtArea.setColumns(20);
        StatusBattleTxtArea.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        StatusBattleTxtArea.setLineWrap(true);
        StatusBattleTxtArea.setRows(5);
        StatusBattleTxtArea.setWrapStyleWord(true);
        StatusBattleTxtArea.setFocusable(false);
        jScrollPane1.setViewportView(StatusBattleTxtArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(17, 290, 271, 106);

        LblPokemonOponente.setFocusable(false);
        getContentPane().add(LblPokemonOponente);
        LblPokemonOponente.setBounds(310, 20, 200, 170);
        if(pokemonOponente.getName().equalsIgnoreCase("Pidgey")){
            setPidgeyImg();
        } else {
            setRattataImg();
        }

        LblFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\NetBeansProjects\\ClonePokemon\\app\\src\\images\\Battle.jpg")); // NOI18N
        getContentPane().add(LblFundo);
        LblFundo.setBounds(-13, -4, 570, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtacarActionPerformed
        // TODO add your handling code here:
		int dano = player.time.get(0).getForca() - (pokemonOponente.getDefense() / 4);
		
		// Garante que o dano mínimo seja 1
		if (dano < 1) {
			dano = 1;
		}
				
		pokemonOponente.setHp(pokemonOponente.getHp() - dano);
		
		if(pokemonOponente.getHp() > 0) {
			StatusBattleTxtArea.setText("Você atacou! e causou de dano: " + dano);
		} else {
			pokemonOponente.setHp(0);
			StatusBattleTxtArea.setText("Você venceu!");
			
			BtnAtacar.setEnabled(false);
			BtnFugir.setEnabled(false);
			
			// Fechar a janela após 5 segundos. Start significa que vai começar :)
			 new Timer(5000, e -> this.dispose()).start();
		}
		
		LblHpOponPokemon.setText(String.valueOf(pokemonOponente.getHp()));
    }//GEN-LAST:event_BtnAtacarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaBatalha().setVisible(true);
			}
		});
	

	}

	
	public void setPidgeyImg() {
    // Caminho da imagem
    String caminhoImagem = "C:\\Users\\gabri\\OneDrive\\Documentos\\NetBeansProjects\\ClonePokemon\\app\\src\\images\\Pidgey-removebg-preview.png";
    
    // Redimensionar a imagem
    ImageIcon originalIcon = new ImageIcon(caminhoImagem);
    Image imagemReduzida = originalIcon.getImage().getScaledInstance(240, 210, Image.SCALE_SMOOTH); // Redimensiona a imagem
    
    // Criar o ImageIcon com a imagem redimensionada
    ImageIcon imagemRedimensionada = new ImageIcon(imagemReduzida);
    
    // Configurar o JLabel
    LblPokemonOponente.setIcon(imagemRedimensionada);
    LblPokemonOponente.setFocusable(false);

    getContentPane().add(LblPokemonOponente);
    LblPokemonOponente.setBounds(290, 20, 240, 210); // Tamanho do JLabel
}

	public void setRattataImg() {
    // Caminho da imagem
    String caminhoImagem = "C:\\Users\\gabri\\OneDrive\\Documentos\\NetBeansProjects\\ClonePokemon\\app\\src\\images\\Rattata-removebg-preview.png";

    // Redimensionar a imagem
    ImageIcon iconOriginal = new ImageIcon(caminhoImagem);
    Image imagemReduzida = iconOriginal.getImage().getScaledInstance(200, 170, Image.SCALE_SMOOTH);

    // Criar um novo ImageIcon com a imagem redimensionada
    LblPokemonOponente.setIcon(new ImageIcon(imagemReduzida));

    // Configurar JLabel
    LblPokemonOponente.setFocusable(false);
    getContentPane().add(LblPokemonOponente);
    LblPokemonOponente.setBounds(310, 20, 200, 170);
}
	
	private Treinador player;
	private Pokemon pokemonOponente;
	private  TelaTeste telaTeste;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtacar;
    private javax.swing.JButton BtnFugir;
    private javax.swing.JLabel LblFundo;
    private javax.swing.JLabel LblHpMyPokemon;
    private javax.swing.JLabel LblHpOponPokemon;
    private javax.swing.JLabel LblNomeMyPokemon;
    private javax.swing.JLabel LblNomeOponPokemon;
    private javax.swing.JLabel LblPokemonOponente;
    private javax.swing.JTextArea StatusBattleTxtArea;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
