/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClonePokemon;

/**
 *
 * @author gabri
 */
public class TelaLaboratorio extends javax.swing.JFrame {

	/**
	 * Creates new form TelaLaboratorio
	 */
	public TelaLaboratorio() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSquirtle = new javax.swing.JButton();
        BtnCharmander = new javax.swing.JButton();
        BtnBulbassaur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DialogueTxtArea = new javax.swing.JTextArea();
        BtnInteracao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(685, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        BtnSquirtle.setBackground(new java.awt.Color(255, 255, 255));
        BtnSquirtle.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        BtnSquirtle.setText("Squirtle");
        BtnSquirtle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        BtnSquirtle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSquirtle.setFocusable(false);
        BtnSquirtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSquirtleActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSquirtle);
        BtnSquirtle.setBounds(440, 390, 100, 40);

        BtnCharmander.setBackground(new java.awt.Color(255, 255, 255));
        BtnCharmander.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        BtnCharmander.setText("Charmander");
        BtnCharmander.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        BtnCharmander.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCharmander.setFocusable(false);
        BtnCharmander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCharmanderActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCharmander);
        BtnCharmander.setBounds(180, 390, 100, 40);

        BtnBulbassaur.setBackground(new java.awt.Color(255, 255, 255));
        BtnBulbassaur.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        BtnBulbassaur.setText("Bulbassaur");
        BtnBulbassaur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        BtnBulbassaur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBulbassaur.setFocusable(false);
        BtnBulbassaur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBulbassaurActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBulbassaur);
        BtnBulbassaur.setBounds(310, 390, 100, 40);

        DialogueTxtArea.setColumns(20);
        DialogueTxtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DialogueTxtArea.setLineWrap(true);
        DialogueTxtArea.setRows(5);
        DialogueTxtArea.setWrapStyleWord(true);
        DialogueTxtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professor Carvalho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        DialogueTxtArea.setCaretColor(new java.awt.Color(51, 51, 255));
        DialogueTxtArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DialogueTxtArea.setFocusable(false);
        jScrollPane1.setViewportView(DialogueTxtArea);
        DialogueTxtArea.setText("""
            Ola! Seja bem-vindo ao incrivel mundo dos Pokemon!
            Meu nome eh Professor Carvalho.
            Sou um pesquisador dedicado ao estudo dessas criaturas fascinantes que compartilham este mundo conosco.
            """);
            BtnCharmander.setVisible(false);
            BtnBulbassaur.setVisible(false);
            BtnSquirtle.setVisible(false);

            getContentPane().add(jScrollPane1);
            jScrollPane1.setBounds(160, 300, 400, 150);

            BtnInteracao.setBackground(new java.awt.Color(255, 255, 255));
            BtnInteracao.setText("...");
            BtnInteracao.setFocusPainted(false);
            BtnInteracao.setFocusable(false);
            BtnInteracao.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnInteracaoActionPerformed(evt);
                }
            });
            getContentPane().add(BtnInteracao);
            BtnInteracao.setBounds(570, 420, 27, 27);

            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATANGABRIELWILDNERD\\Documents\\NetBeansProjects\\ClonePokemon\\app\\src\\images\\ProfessorOak2.png")); // NOI18N
            getContentPane().add(jLabel2);
            jLabel2.setBounds(40, 0, 637, 1097);

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents
	
	public int stage = 0;
    private void BtnInteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInteracaoActionPerformed
        // TODO add your handling code here:
		switch(stage) {
			case 0:
				DialogueTxtArea.setText("""
                        Hoje, eh um dia muito especial: voce esta prestes a iniciar sua jornada como treinador Pokemon! 
                        Mas, antes de partir, voce precisara de um companheiro para acompanha-lo nessa aventura.                         
                          """);
				stage++;
				break;
				
			case 1:
				DialogueTxtArea.setText("""                       
                        Aqui estao tres Pokemon iniciais. Cada um deles possui habilidades unicas e personalidades diferentes. Escolha com sabedoria!
                          """);
				
				BtnInteracao.setVisible(false);
				BtnCharmander.setVisible(true);
				BtnBulbassaur.setVisible(true);
				BtnSquirtle.setVisible(true);

				stage++;								
				break;
				
			case 3:
				DialogueTxtArea.setText("""
			O mundo dos Pokemon esta repleto de desafios, batalhas e descobertas incriveis. 
			Confie no seu Pokemon e no seu instinto, e tenho certeza de que voce sera bem-sucedido.
			Boa sorte! Vou ficar ansioso para ouvir sobre suas aventuras. 
			Ah, e nao se esqueca de vir me visitar de vez em quando para me contar o que encontrou por ai! 
                            """);
				stage++;
				
				
				break;
				
			case 4:
				TelaTeste telaTest = new TelaTeste(player);
				this.dispose();
				telaTest.setVisible(true);
				
				break;
		}
    }//GEN-LAST:event_BtnInteracaoActionPerformed

    private void BtnSquirtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSquirtleActionPerformed
        // TODO add your handling code here:
		player.adicionarAoTime(new Pokemon("Squirtle", 20, 20, 20, 20));
		
		BtnInteracao.setVisible(true);
				BtnCharmander.setVisible(false);
				BtnBulbassaur.setVisible(false);
				BtnSquirtle.setVisible(false);
				
		setDialogueTxtAreaAfterChose();		
    }//GEN-LAST:event_BtnSquirtleActionPerformed

    private void BtnCharmanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCharmanderActionPerformed
        // TODO add your handling code here:
		player.adicionarAoTime(new Pokemon("Charmander", 20, 20, 20, 20));
		BtnInteracao.setVisible(true);
				BtnCharmander.setVisible(false);
				BtnBulbassaur.setVisible(false);
				BtnSquirtle.setVisible(false);
				
		setDialogueTxtAreaAfterChose();
    }//GEN-LAST:event_BtnCharmanderActionPerformed

    private void BtnBulbassaurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBulbassaurActionPerformed
        // TODO add your handling code here:
		player.adicionarAoTime(new Pokemon("Bulbassaur", 20, 20, 20, 20));
		BtnInteracao.setVisible(true);
				BtnCharmander.setVisible(false);
				BtnBulbassaur.setVisible(false);
				BtnSquirtle.setVisible(false);
				
		setDialogueTxtAreaAfterChose();
    }//GEN-LAST:event_BtnBulbassaurActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaLaboratorio().setVisible(true);
			}
		});
		
		
	}
	
	private void setDialogueTxtAreaAfterChose(){
		DialogueTxtArea.setText("""
                          Boa Escolha!
                         Agora, sua jornada esta prestes a comecar.                          
                          """);
		stage++;
		
	}
	
	
	public Treinador player = new Treinador("Jogador1");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBulbassaur;
    private javax.swing.JButton BtnCharmander;
    private javax.swing.JButton BtnInteracao;
    private javax.swing.JButton BtnSquirtle;
    private javax.swing.JTextArea DialogueTxtArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
