/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClonePokemon;

/**
 *
 * @author gabri
 */
public class TelaLaboratorio extends javax.swing.JFrame {

	/**
	 * Creates new form TelaLaboratorio
	 */
	public TelaLaboratorio() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DialogueTxtArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(685, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        DialogueTxtArea.setColumns(20);
        DialogueTxtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DialogueTxtArea.setLineWrap(true);
        DialogueTxtArea.setRows(5);
        DialogueTxtArea.setWrapStyleWord(true);
        DialogueTxtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professor Carvalho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        DialogueTxtArea.setCaretColor(new java.awt.Color(51, 51, 255));
        DialogueTxtArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DialogueTxtArea.setFocusable(false);
        jScrollPane1.setViewportView(DialogueTxtArea);
        DialogueTxtArea.setText("""
            Ola! Seja bem-vindo ao incrivel mundo dos Pokemon!
            Meu nome eh Professor Carvalho.
            Sou um pesquisador dedicado ao estudo dessas criaturas fascinantes que compartilham este mundo conosco.
            """);

            getContentPane().add(jScrollPane1);
            jScrollPane1.setBounds(160, 300, 400, 150);

            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\NetBeansProjects\\ClonePokemon\\app\\src\\main\\java\\Images\\ProfessorOak2.png")); // NOI18N
            getContentPane().add(jLabel2);
            jLabel2.setBounds(40, 0, 637, 1097);

            pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaLaboratorio().setVisible(true);
			}
		});
		
		
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DialogueTxtArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
