/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.biblioMVC;

import com.example.biblioMVC.model.ConexaoSQLiteModel;

import com.example.biblioMVC.view.*;

import java.sql.Connection;

public class App {
	Connection conexao = ConexaoSQLiteModel.conectar();
	
	
	public static void main(String[] args) {
		new Frmlivro().main(args);
	}
}