/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dotenv;


import com.formdev.flatlaf.FlatDarkLaf;
import dotenv.view.AutenticacaoForm;
import javax.swing.UIManager;

public class App {

	public static void main(String[] args) {
		try{
			UIManager.setLookAndFeel(new FlatDarkLaf());
		} catch (Exception e) {
			System.err.println("Erro ao setar tema: "  + e.getMessage());
		}
		
		new AutenticacaoForm().setVisible(true);
	}
}
