/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dotenv;

import dotenv.database.Database;

public class App {

	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		Database db = new Database();
	}
}
