/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExpenseManager;


import ExpenseManager.model.Cost;
import ExpenseManager.Controller.CostController;

public class App {
	
	public static void main(String[] args) {
		CostController CostController = new CostController();
		
		Cost costNew = new Cost("Agropecuária", "Compramos ração e areia pra gatos.", "Agropecuária", 89.89, "11/03/2025");
		
		CostController.saveCost(costNew);

	}
}
