/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dotenv.view;

import java.awt.Color;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author NATANGABRIELWILDNERD
 */
public class AutenticacaoForm extends javax.swing.JFrame {

	/**
	 * Creates new form AutenticacaoForm
	 */
	
	private static final LineBorder RED_BORDER = new LineBorder(Color.RED, 1);
	
	public AutenticacaoForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titleName = new javax.swing.JLabel();
        titleLastName = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputSobrenome = new javax.swing.JTextField();
        titleEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        titlePassword = new javax.swing.JLabel();
        titlePassword2 = new javax.swing.JLabel();
        inputSenha1 = new javax.swing.JPasswordField();
        inputSenha2 = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        optLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setText("Create a Account");

        titleName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titleName.setText("First name:");

        titleLastName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titleLastName.setText("Last name:");

        inputNome.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        inputNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        inputNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNomeFocusLost(evt);
            }
        });
        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        inputSobrenome.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        inputSobrenome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        inputSobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputSobrenomeFocusLost(evt);
            }
        });

        titleEmail.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titleEmail.setText("Email:");

        inputEmail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        inputEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailFocusLost(evt);
            }
        });

        titlePassword.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titlePassword.setText("Password:");

        titlePassword2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titlePassword2.setText("Confirm Password");

        inputSenha1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        inputSenha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        inputSenha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputSenha1FocusLost(evt);
            }
        });

        inputSenha2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        inputSenha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnRegister.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        optLogin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 10)); // NOI18N
        optLogin.setText("Already a account?");

        javax.swing.GroupLayout PanelRegisterLayout = new javax.swing.GroupLayout(PanelRegister);
        PanelRegister.setLayout(PanelRegisterLayout);
        PanelRegisterLayout.setHorizontalGroup(
            PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(PanelRegisterLayout.createSequentialGroup()
                        .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRegisterLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titlePassword)
                                    .addComponent(inputSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlePassword2)
                            .addComponent(inputSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelRegisterLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelRegisterLayout.createSequentialGroup()
                                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleName)
                                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLastName)
                                    .addComponent(inputSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelRegisterLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(titleEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputEmail))
                            .addComponent(optLogin))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        PanelRegisterLayout.setVerticalGroup(
            PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegisterLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleName)
                            .addComponent(titleLastName)))
                    .addGroup(PanelRegisterLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleEmail))
                .addGap(18, 18, 18)
                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titlePassword)
                        .addComponent(titlePassword2))
                    .addGroup(PanelRegisterLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelMain.add(PanelRegister, "cardRegister");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
		// TODO add your handling code here:
		ArrayList<JTextField> inputList = new ArrayList();
		inputList.add(inputNome);
		inputList.add(inputSobrenome);
		inputList.add(inputEmail);

		if (checkInputsEmpty(inputList)) {
			JOptionPane.showMessageDialog(rootPane, "Há campos em branco!", "Aviso", JOptionPane.WARNING_MESSAGE);
			return;
		}

		String user_name = inputNome.getText();
		String user_email = inputEmail.getText();
		String user_password = String.valueOf(inputSenha1.getPassword());
		String user_password2 = String.valueOf(inputSenha2.getPassword());
		
		if(!user_password.equals(user_password2)) {
			JOptionPane.showMessageDialog(rootPane, "Senhas não coincidem!", "Aviso", JOptionPane.WARNING_MESSAGE);
			inputSenha2.setBorder(new LineBorder(Color.RED, 2));
			return;
		}
		
		

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void inputNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNomeFocusLost
        // TODO add your handling code here:
		checkBorderRed(this.inputNome);
    }//GEN-LAST:event_inputNomeFocusLost

    private void inputSobrenomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSobrenomeFocusLost
        // TODO add your handling code here:
		checkBorderRed(this.inputSobrenome);
    }//GEN-LAST:event_inputSobrenomeFocusLost

    private void inputEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusLost
        // TODO add your handling code here:
		checkBorderRed(this.inputEmail);
    }//GEN-LAST:event_inputEmailFocusLost

    private void inputSenha1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSenha1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSenha1FocusLost

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AutenticacaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AutenticacaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AutenticacaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AutenticacaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AutenticacaoForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelRegister;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNome;
    private javax.swing.JPasswordField inputSenha1;
    private javax.swing.JPasswordField inputSenha2;
    private javax.swing.JTextField inputSobrenome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel optLogin;
    private javax.swing.JLabel titleEmail;
    private javax.swing.JLabel titleLastName;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titlePassword;
    private javax.swing.JLabel titlePassword2;
    // End of variables declaration//GEN-END:variables

	private boolean checkInputsEmpty(ArrayList<javax.swing.JTextField> inputList) {
		boolean anyEmpty = false;
		for (JTextField input : inputList) {
			if (input.getText().isEmpty()) {
				input.setBorder(RED_BORDER);
				anyEmpty = true;
			} else {
				input.setBorder(new LineBorder(new java.awt.Color(153, 153, 153)));
			}
			
		}
		return anyEmpty;
	}
	
	private void checkBorderRed(javax.swing.JTextField input){
		if(inputNome.getBorder() == RED_BORDER){
			inputNome.setBorder(new LineBorder(new java.awt.Color(153, 153, 153)));
		}
	}
}
