/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.JvaEmail.view;

import com.example.JvaEmail.controller.UsuarioController;
import com.example.JvaEmail.model.Usuario;
import com.formdev.flatlaf.ui.FlatBorder;
import com.formdev.flatlaf.ui.FlatTextBorder;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.border.LineBorder;
import javax.swing.text.JTextComponent;

/**
 *
 * @author gabri
 */
public class Autenticacao extends javax.swing.JFrame {

	/**
	 * Creates new form Autenticacao
	 */
	private final UsuarioController usuarioController = new UsuarioController();

	public Autenticacao() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        PanelForms = new javax.swing.JPanel();
        RegisterForm = new javax.swing.JPanel();
        titleCard = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        titleEmail = new javax.swing.JLabel();
        titleNome = new javax.swing.JLabel();
        titlePassword = new javax.swing.JLabel();
        inputEmailR = new javax.swing.JTextField();
        inputName = new javax.swing.JTextField();
        inputPasswordR = new javax.swing.JPasswordField();
        btnCreate = new javax.swing.JButton();
        btnToLogin = new javax.swing.JButton();
        LoginForm = new javax.swing.JPanel();
        titleCard1 = new javax.swing.JLabel();
        subTitle1 = new javax.swing.JLabel();
        titleEmail1 = new javax.swing.JLabel();
        titlePassword1 = new javax.swing.JLabel();
        inputEmailL = new javax.swing.JTextField();
        inputPasswordL = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnToRegister = new javax.swing.JButton();
        titlePassword3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JvaEmail - Credenciais");

        logo.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        logo.setText("Jva-Email");

        PanelForms.setLayout(new java.awt.CardLayout());

        titleCard.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        titleCard.setText("Junte-se á nós!");

        subTitle.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        subTitle.setText("É Rápido e Fácil.");

        titleEmail.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titleEmail.setText("Crie seu email:");

        titleNome.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titleNome.setText("Informe seu nome:");

        titlePassword.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titlePassword.setText("Agora, sua senha:");

        inputEmailR.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        inputEmailR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailRFocusLost(evt);
            }
        });

        inputName.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        inputName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNameFocusLost(evt);
            }
        });

        inputPasswordR.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        inputPasswordR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPasswordRFocusLost(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnCreate.setText("Criar Conta");
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreate.setDoubleBuffered(true);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnToLogin.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        btnToLogin.setText("Já Possui ?");
        btnToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterFormLayout = new javax.swing.GroupLayout(RegisterForm);
        RegisterForm.setLayout(RegisterFormLayout);
        RegisterFormLayout.setHorizontalGroup(
            RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleCard)
                    .addGroup(RegisterFormLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subTitle)
                            .addComponent(titleEmail)
                            .addComponent(titleNome)
                            .addComponent(titlePassword)
                            .addComponent(inputEmailR)
                            .addComponent(inputName, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(inputPasswordR)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisterFormLayout.setVerticalGroup(
            RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterFormLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTitle)
                .addGap(18, 18, 18)
                .addComponent(titleEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmailR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titlePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPasswordR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelForms.add(RegisterForm, "registerForm");

        titleCard1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        titleCard1.setText("Que bom que voltou!");

        subTitle1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        subTitle1.setText("Fico feliz que estás de volta.");

        titleEmail1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titleEmail1.setText("Digite Seu Email:");

        titlePassword1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        titlePassword1.setText("Agora, sua senha:");

        inputEmailL.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        inputEmailL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailLFocusLost(evt);
            }
        });

        inputPasswordL.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        inputPasswordL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPasswordLFocusLost(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnLogin.setText("Entrar");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setDoubleBuffered(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnToRegister.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        btnToRegister.setText("Ainda não possui ?");
        btnToRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToRegisterActionPerformed(evt);
            }
        });

        titlePassword3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        titlePassword3.setText("Esqueceu a senha?");
        titlePassword3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titlePassword3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePassword3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleCard1)
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subTitle1)
                            .addComponent(titleEmail1)
                            .addComponent(titlePassword1)
                            .addComponent(inputEmailL)
                            .addComponent(inputPasswordL)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(btnToRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlePassword3)
                .addContainerGap())
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleCard1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTitle1)
                .addGap(18, 18, 18)
                .addComponent(titleEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmailL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titlePassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titlePassword3)
                .addGap(60, 60, 60)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        PanelForms.add(LoginForm, "loginForm");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logo)
                .addGap(50, 50, 50)
                .addComponent(PanelForms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelForms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
		// TODO add your handling code here:
		ArrayList<JTextComponent> list = new ArrayList();
		list.add(inputEmailR);
		list.add(inputName);
		list.add(inputPasswordR);

		if (checkAnyEmpty(list)) {
			JOptionPane.showMessageDialog(this, "Por Favor, preencha todos os campos!", "Ops...", JOptionPane.WARNING_MESSAGE);
			return;
		}

		String respC = usuarioController.registar(inputEmailR.getText().trim(),
				inputName.getText().trim(),
				String.valueOf(inputPasswordR.getPassword()).trim());

		if (usuarioController.hasError()) {
			JOptionPane.showMessageDialog(this, this.usuarioController.getError(), "Ops...", JOptionPane.ERROR_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(this, respC, "Bem-Vindo!", JOptionPane.INFORMATION_MESSAGE);
			inputEmailR.setText("");
			inputName.setText("");
			inputPasswordR.setText("");
		}
    }//GEN-LAST:event_btnCreateActionPerformed

    private void inputEmailRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailRFocusLost
		// TODO add your handling code here:
		checkBorderRed(inputEmailR);
    }//GEN-LAST:event_inputEmailRFocusLost

    private void inputNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNameFocusLost
		// TODO add your handling code here:
		checkBorderRed(inputName);
    }//GEN-LAST:event_inputNameFocusLost

    private void inputPasswordRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordRFocusLost
		// TODO add your handling code here:
		checkBorderRed(inputPasswordR);
    }//GEN-LAST:event_inputPasswordRFocusLost

    private void inputEmailLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailLFocusLost
		// TODO add your handling code here:
    }//GEN-LAST:event_inputEmailLFocusLost

    private void inputPasswordLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordLFocusLost
		// TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordLFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
		// TODO add your handling code here:
		ArrayList<JTextComponent> list = new ArrayList();
		list.add(inputEmailL);
		list.add(inputPasswordL);

		if (checkAnyEmpty(list)) {
			JOptionPane.showMessageDialog(this, "Por Favor, preencha todos os campos!", "Ops...", JOptionPane.WARNING_MESSAGE);
			return;
		}

		Usuario usuarioLocal = this.usuarioController.login(inputEmailL.getText().trim(),
				String.valueOf(inputPasswordL.getPassword()).trim());

		if (this.usuarioController.hasError()) {
			JOptionPane.showMessageDialog(this, this.usuarioController.getError(), "Ops...", JOptionPane.ERROR_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(this, "Login efetuado com sucesso!", "Bem-Vindo Novamente", JOptionPane.INFORMATION_MESSAGE);
			this.dispose();
			new JvaHome(usuarioController, usuarioLocal).setVisible(true);
		}
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToRegisterActionPerformed
		// TODO add your handling code here:
		changeCard(0);
    }//GEN-LAST:event_btnToRegisterActionPerformed

    private void btnToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLoginActionPerformed
		// TODO add your handling code here:
		changeCard(1);
    }//GEN-LAST:event_btnToLoginActionPerformed

    private void titlePassword3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePassword3MouseClicked
		// TODO add your handling code here:
		ArrayList<JTextComponent> list = new ArrayList();
		list.add(inputEmailL);

		if (checkAnyEmpty(list)) {
			JOptionPane.showMessageDialog(this, "Preencha com seu email.\nApós preencher, clique aqui novamente.", "Instruções", JOptionPane.QUESTION_MESSAGE);
			return;
		}

		boolean respC = this.usuarioController.checkExists(inputEmailL.getText().trim());

		if (this.usuarioController.hasError()) {
			JOptionPane.showMessageDialog(this, this.usuarioController.getError(), "Ops...", JOptionPane.ERROR_MESSAGE);
			return;
		}

		if (!respC) {
			JOptionPane.showMessageDialog(this, "O email que você digitou não está cadastrado!", "Verifique seu email", JOptionPane.ERROR_MESSAGE);
		} else {
			String novaSenha = JOptionPane.showInputDialog(this, "Digite sua nova senha: \n- Não se preocupe, ela não será visível no banco de dados.", "Redefinir Senha", JOptionPane.PLAIN_MESSAGE);

			if (!novaSenha.equals("")) {
				String respUpd = this.usuarioController.atualizarSenha(inputEmailL.getText().trim(), novaSenha.trim());

				if (usuarioController.hasError()) {
					JOptionPane.showMessageDialog(this, this.usuarioController.getError(), "Ops...", JOptionPane.ERROR_MESSAGE);
				} else {
					JOptionPane.showMessageDialog(this, respUpd, "Operação Realizada", JOptionPane.INFORMATION_MESSAGE);
				}
			}
		}
    }//GEN-LAST:event_titlePassword3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginForm;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelForms;
    private javax.swing.JPanel RegisterForm;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnToLogin;
    private javax.swing.JButton btnToRegister;
    private javax.swing.JTextField inputEmailL;
    private javax.swing.JTextField inputEmailR;
    private javax.swing.JTextField inputName;
    private javax.swing.JPasswordField inputPasswordL;
    private javax.swing.JPasswordField inputPasswordR;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel subTitle1;
    private javax.swing.JLabel titleCard;
    private javax.swing.JLabel titleCard1;
    private javax.swing.JLabel titleEmail;
    private javax.swing.JLabel titleEmail1;
    private javax.swing.JLabel titleNome;
    private javax.swing.JLabel titlePassword;
    private javax.swing.JLabel titlePassword1;
    private javax.swing.JLabel titlePassword3;
    // End of variables declaration//GEN-END:variables

	private boolean checkAnyEmpty(ArrayList<JTextComponent> list) {
		boolean anyEmpty = false;

		for (JTextComponent txtcm : list) {
			if (txtcm.getText().isEmpty() && txtcm.isEnabled()) {
				anyEmpty = true;
				txtcm.setBorder(new LineBorder(Color.red, 1));
			}
		}

		return anyEmpty;
	}

	private void checkBorderRed(JTextComponent txtcm) {
		if (txtcm.getBorder() instanceof LineBorder border) {
			if (border.getLineColor().equals(Color.red)) {
				boolean isEmpty;

				if (txtcm instanceof JPasswordField) {
					isEmpty = ((JPasswordField) txtcm).getPassword().length == 0;
				} else {
					isEmpty = txtcm.getText().isEmpty();
				}

				if (!isEmpty) {
					txtcm.setBorder(new FlatTextBorder());
				}
			}
		}
	}

	private void changeCard(int id) {

		//1 -> Login
		//0 -> Registro
		CardLayout cl = (CardLayout) PanelForms.getLayout();

		switch (id) {
			case 0:
				cl.show(PanelForms, "registerForm");
				inputEmailL.setText("");
				inputPasswordL.setText("");
				break;
			case 1:
				cl.show(PanelForms, "loginForm");
				inputEmailR.setText("");
				inputName.setText("");
				inputPasswordR.setText("");
				break;
			default:
				throw new AssertionError();
		}
	}
}
