/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.JvaEmail.view;

import com.example.JvaEmail.controller.EmailController;
import com.example.JvaEmail.controller.UsuarioController;
import com.example.JvaEmail.model.Email;
import com.example.JvaEmail.model.Usuario;
import com.formdev.flatlaf.ui.FlatTextBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.border.LineBorder;
import javax.swing.text.JTextComponent;

/**
 *
 * @author gabri
 */
public class JvaHome extends javax.swing.JFrame {

	/**
	 * Creates new form JvaHome
	 */
	private Usuario usuarioLogado;
	private EmailController emailController = new EmailController();
	private UsuarioController usuarioController;

	public JvaHome(UsuarioController usuarioController, Usuario usuarioLogado) {
		this.usuarioLogado = usuarioLogado;
		this.usuarioController = usuarioController;
		initComponents();
		attTableEmails();
	}

	public JvaHome() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ToolbarPanel = new javax.swing.JPanel();
        btnInbox = new javax.swing.JButton();
        btnCompose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ScrollPaneEmails = new javax.swing.JScrollPane();
        tableListaEmails = new javax.swing.JTable();
        ComposePanel = new javax.swing.JPanel();
        titleDesti = new javax.swing.JLabel();
        titleTitulo = new javax.swing.JLabel();
        titleConteudo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConteudo = new javax.swing.JTextArea();
        inputTitulo = new javax.swing.JTextField();
        comboBoxDest = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        DetalhesPanel = new javax.swing.JPanel();
        titleRem = new javax.swing.JLabel();
        titleTitle = new javax.swing.JLabel();
        titleCont = new javax.swing.JLabel();
        idEmail = new javax.swing.JLabel();
        inputRemDetalhes = new javax.swing.JTextField();
        inputTituloDetalhes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        corpoDetalhes = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JvaEmail-Home");

        btnInbox.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        btnInbox.setText("📩   Caixa de Entrada");
        btnInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToolbarPanelLayout = new javax.swing.GroupLayout(ToolbarPanel);
        ToolbarPanel.setLayout(ToolbarPanelLayout);
        ToolbarPanelLayout.setHorizontalGroup(
            ToolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ToolbarPanelLayout.setVerticalGroup(
            ToolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnInbox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        btnCompose.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnCompose.setText("✏    Escrever");
        btnCompose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComposeActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        ScrollPaneEmails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caixa de Entrada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12))); // NOI18N
        ScrollPaneEmails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ScrollPaneEmailsKeyPressed(evt);
            }
        });

        tableListaEmails.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        tableListaEmails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Quem enviou", "Título do Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListaEmails.setShowGrid(false);
        tableListaEmails.setShowHorizontalLines(true);
        tableListaEmails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListaEmailsMouseClicked(evt);
            }
        });
        tableListaEmails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableListaEmailsKeyPressed(evt);
            }
        });
        ScrollPaneEmails.setViewportView(tableListaEmails);

        jPanel1.add(ScrollPaneEmails, "scrollEmails");

        ComposePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escrevendo um email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12))); // NOI18N

        titleDesti.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        titleDesti.setText("Destinatário:");

        titleTitulo.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        titleTitulo.setText("Título:");

        titleConteudo.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        titleConteudo.setText("Conteúdo:");

        txtConteudo.setColumns(20);
        txtConteudo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        txtConteudo.setRows(5);
        jScrollPane1.setViewportView(txtConteudo);

        inputTitulo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N

        comboBoxDest.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        for(Usuario u : this.usuarioController.listarUsuarios()){
            modelo.addElement(u.getEmail());
        }
        comboBoxDest.setModel(modelo);

        btnEnviar.setBackground(new java.awt.Color(51, 204, 0));
        btnEnviar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        btnEnviar.setText("📤");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ComposePanelLayout = new javax.swing.GroupLayout(ComposePanel);
        ComposePanel.setLayout(ComposePanelLayout);
        ComposePanelLayout.setHorizontalGroup(
            ComposePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComposePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComposePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(ComposePanelLayout.createSequentialGroup()
                        .addComponent(titleTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTitulo))
                    .addGroup(ComposePanelLayout.createSequentialGroup()
                        .addComponent(titleConteudo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ComposePanelLayout.createSequentialGroup()
                        .addComponent(titleDesti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxDest, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComposePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ComposePanelLayout.setVerticalGroup(
            ComposePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComposePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ComposePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleDesti)
                    .addComponent(comboBoxDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ComposePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleTitulo)
                    .addComponent(inputTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(titleConteudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addContainerGap())
        );

        jPanel1.add(ComposePanel, "composeCard");

        DetalhesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12))); // NOI18N

        titleRem.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        titleRem.setText("Remetente:");

        titleTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        titleTitle.setText("Título:");

        titleCont.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        titleCont.setText("Conteúdo:");

        idEmail.setText("jLabel1");
        idEmail.setVisible(false);

        inputRemDetalhes.setEditable(false);
        inputRemDetalhes.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        inputRemDetalhes.setText("jTextField1");

        inputTituloDetalhes.setEditable(false);
        inputTituloDetalhes.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        inputTituloDetalhes.setText("jTextField1");

        corpoDetalhes.setEditable(false);
        corpoDetalhes.setColumns(20);
        corpoDetalhes.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        corpoDetalhes.setRows(5);
        jScrollPane2.setViewportView(corpoDetalhes);

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        btnDelete.setText("🗑");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetalhesPanelLayout = new javax.swing.GroupLayout(DetalhesPanel);
        DetalhesPanel.setLayout(DetalhesPanelLayout);
        DetalhesPanelLayout.setHorizontalGroup(
            DetalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetalhesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DetalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetalhesPanelLayout.createSequentialGroup()
                        .addComponent(titleRem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputRemDetalhes))
                    .addGroup(DetalhesPanelLayout.createSequentialGroup()
                        .addComponent(titleTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTituloDetalhes))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(DetalhesPanelLayout.createSequentialGroup()
                        .addGroup(DetalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleCont)
                            .addComponent(idEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DetalhesPanelLayout.setVerticalGroup(
            DetalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetalhesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DetalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleRem)
                    .addComponent(inputRemDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(DetalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleTitle)
                    .addComponent(inputTituloDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(titleCont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetalhesPanelLayout.createSequentialGroup()
                        .addComponent(idEmail)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(DetalhesPanel, "detalhesCard");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToolbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCompose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(btnCompose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToolbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInboxActionPerformed
		// TODO add your handling code here:
		CardLayout cl = (CardLayout) jPanel1.getLayout();
		cl.show(jPanel1, "scrollEmails");

		attTableEmails();
    }//GEN-LAST:event_btnInboxActionPerformed

    private void btnComposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComposeActionPerformed
		// TODO add your handling code here:
		CardLayout cl = (CardLayout) jPanel1.getLayout();
		cl.show(jPanel1, "composeCard");
    }//GEN-LAST:event_btnComposeActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
		// TODO add your handling code here:
		ArrayList<JTextComponent> list = new ArrayList();
		list.add(txtConteudo);
		list.add(inputTitulo);
		if (checkAnyEmpty(list)) {
			JOptionPane.showMessageDialog(this, "Preencha com seu email.\nApós preencher, clique aqui novamente.", "Instruções", JOptionPane.QUESTION_MESSAGE);
			return;
		}

		String respC = this.emailController.enviarEmail(usuarioLogado,
				String.valueOf(comboBoxDest.getSelectedItem()),
				inputTitulo.getText(),
				txtConteudo.getText());

		if (this.emailController.hasError()) {
			JOptionPane.showMessageDialog(this, this.emailController.getError(), "Ops...", JOptionPane.ERROR_MESSAGE);
			return;
		}

		JOptionPane.showMessageDialog(this, respC, "Enviado!", JOptionPane.INFORMATION_MESSAGE);

		inputTitulo.setText("");
		txtConteudo.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void ScrollPaneEmailsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScrollPaneEmailsKeyPressed
		// TODO add your handling code here:
		//Evento para abrir os detalhes

    }//GEN-LAST:event_ScrollPaneEmailsKeyPressed

    private void tableListaEmailsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableListaEmailsKeyPressed
		// TODO add your handling code here:
		if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
			int linhaSelecionda = tableListaEmails.getSelectedRow();
			System.out.println(linhaSelecionda);

			if (linhaSelecionda != -1) {
				String nomeRem = (String) tableListaEmails.getValueAt(linhaSelecionda, 0);
				String tituloEmail = (String) tableListaEmails.getValueAt(linhaSelecionda, 1);

				Email email4open = this.emailController.abrirDetalhes(nomeRem, tituloEmail);

				if (email4open != null) {
					CardLayout cl = (CardLayout) jPanel1.getLayout();
					cl.show(jPanel1, "detalhesCard");

					inputRemDetalhes.setText(email4open.getDestinatario().getEmail());
					inputTituloDetalhes.setText(email4open.getTitulo());
					corpoDetalhes.setText(email4open.getConteudo());
					idEmail.setText("" + email4open.getId());
				}
			}
		}
    }//GEN-LAST:event_tableListaEmailsKeyPressed

    private void tableListaEmailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListaEmailsMouseClicked
		// TODO add your handling code here:
		int linhaSelecionda = tableListaEmails.getSelectedRow();
		System.out.println(linhaSelecionda);

		if (linhaSelecionda != -1) {
			String nomeRem = (String) tableListaEmails.getValueAt(linhaSelecionda, 0);
			String tituloEmail = (String) tableListaEmails.getValueAt(linhaSelecionda, 1);

			Email email4open = this.emailController.abrirDetalhes(nomeRem, tituloEmail);

			if (email4open != null) {
				CardLayout cl = (CardLayout) jPanel1.getLayout();
				cl.show(jPanel1, "detalhesCard");

				inputRemDetalhes.setText(email4open.getDestinatario().getEmail());
				inputTituloDetalhes.setText(email4open.getTitulo());
				corpoDetalhes.setText(email4open.getConteudo());
				idEmail.setText("" + email4open.getId());
			}
		}
    }//GEN-LAST:event_tableListaEmailsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
		int idEmail = Integer.parseInt(this.idEmail.getText());
		
		String respC = this.emailController.deletarEmail(idEmail);
		
		if(this.emailController.hasError()){
			//Option erro
			return;
		}
		
		JOptionPane.showMessageDialog(this, respC, "Deletar Email", JOptionPane.INFORMATION_MESSAGE);
		CardLayout cl = (CardLayout) jPanel1.getLayout();
		cl.show(jPanel1, "scrollEmails");
		attTableEmails();
    }//GEN-LAST:event_btnDeleteActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JvaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JvaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JvaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JvaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JvaHome().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ComposePanel;
    private javax.swing.JPanel DetalhesPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane ScrollPaneEmails;
    private javax.swing.JPanel ToolbarPanel;
    private javax.swing.JButton btnCompose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnInbox;
    private javax.swing.JComboBox<String> comboBoxDest;
    private javax.swing.JTextArea corpoDetalhes;
    private javax.swing.JLabel idEmail;
    private javax.swing.JTextField inputRemDetalhes;
    private javax.swing.JTextField inputTitulo;
    private javax.swing.JTextField inputTituloDetalhes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableListaEmails;
    private javax.swing.JLabel titleCont;
    private javax.swing.JLabel titleConteudo;
    private javax.swing.JLabel titleDesti;
    private javax.swing.JLabel titleRem;
    private javax.swing.JLabel titleTitle;
    private javax.swing.JLabel titleTitulo;
    private javax.swing.JTextArea txtConteudo;
    // End of variables declaration//GEN-END:variables

	private void attTableEmails() {
		DefaultTableModel modelo = (DefaultTableModel) tableListaEmails.getModel();

		this.emailController.attEmailsRecebidos(usuarioLogado);

		if (this.emailController.haveAnyEmail()) {
			modelo.setRowCount(0);
			for (Email email4 : this.emailController.listarEmailsRecebidos()) {
				modelo.addRow(new Object[]{email4.getRemetente().getNome(), email4.getTitulo()});
			}
		}
	}

	private boolean checkAnyEmpty(ArrayList<JTextComponent> list) {
		boolean anyEmpty = false;

		for (JTextComponent txtcm : list) {
			if (txtcm.getText().isEmpty() && txtcm.isEnabled()) {
				anyEmpty = true;
				txtcm.setBorder(new LineBorder(Color.red, 1));
			}
		}

		return anyEmpty;
	}

	private void checkBorderRed(JTextComponent txtcm) {
		if (txtcm.getBorder() instanceof LineBorder border) {
			if (border.getLineColor().equals(Color.red)) {
				boolean isEmpty;

				if (txtcm instanceof JPasswordField) {
					isEmpty = ((JPasswordField) txtcm).getPassword().length == 0;
				} else {
					isEmpty = txtcm.getText().isEmpty();
				}

				if (!isEmpty) {
					txtcm.setBorder(new FlatTextBorder());
				}
			}
		}
	}
}
