/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BiblioMVC;

import BiblioMVC.model.ConexaoSQLite;
import java.sql.Connection;

public class App {

	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		Connection conexao = ConexaoSQLite.conectar();
		ConexaoSQLite.criarTabela(conexao);
	}
}
